deseos = ['Londres', 'Oslo', 'San Francisco', 'Nueva York', 'Tokio']
print(f'Lista en su orden original: {deseos}.')
print(f'Lista ordenada alfabeticamente de forma temporal: {sorted(deseos)}.')
print(f'Comprobamos que su orden sigue siendo el original: {deseos}.')
print(f'Orden alf. inverso temporal: {sorted(deseos, reverse=True)}.')
print(f'Comprobamos que su orden sigue siendo el original: {deseos}.')
deseos.reverse()
print(f'Mostramos la lista tras haber invertido su orden de forma permanente: {deseos}.')
deseos.reverse()
print(f'Hemos vuelto a aplicar reverse, comprobamos que ha vuelto al orden inicial: {deseos}.')
deseos.sort()
print(f'Hemos ordenado alfabeticamente y de forma permanente: {deseos}.')
deseos.sort(reverse=True)
print(f'Hemos ordenado alf, inversa y de forma permanente: {deseos}.')